sparse: Add 'artifical' to ignore attributes
This patch adds the 'artifical' GCC attribute to list of ignore attributes.
It's an attribute that's used by glibc which causes the following bogus sparse
warnings when using it for userspace projects:

  /usr/include/bits/stdlib.h:37:1: error: attribute '__artificial__': unknown attribute
  /usr/include/bits/stdlib.h:64:1: error: attribute '__artificial__': unknown attribute

Signed-off-by: Pekka Enberg <penberg@kernel.org>
Signed-off-by: Christopher Li <sparse@chrisli.org>