pre-process: fix build error in gcc-11 and gcc-12
pre-process.c: In function ‘parse_expansion’:
pre-process.c:1648:16: error: variable-sized object may not be initialized
 1648 |         struct arg_state args[slots] = {};
      |                ^~~~~~~~~

Older versions of GCC will not allow a variable length array to have
an initializer.  This was changed in gcc-13 and later.  Change the
initializer to a memset() to fix the build.

Reported-by: Harshit Mogalapalli <harshit.m.mogalapalli@oracle.com>
Signed-off-by: Dan Carpenter <error27@gmail.com>