expand more builtins like __builtin_ffs()
GCC expands at compile time builtins like __builtin_ffs()
when their argument is constant.

A driver in the kernel uses such a builtin in a case statement,
causing sparse to report:
	error: Expected constant expression in case statement

So, let sparse also expand such builtins, somehow like it was
done for bswap16/32/64 but now for ffs/ffsl/ffsll, clz, ctz,
clrsb, popcount & parity.

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Luc Van Oostenryck <luc.vanoostenryck@gmail.com>
Tested-by: Randy Dunlap <rdunlap@infradead.org>