data: add snprintf to kernel.sizeof_param.remove
This was causing all kinds of false positives like:

include/trace/events/sched.h:117 ftrace_define_fields_sched_switch()
	error: snprintf() '"char"' too small (5 vs 128)

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>