recognize binary constants
Sparse doesn't parse binary constants properly so the following code
generates an error:

	x = 0b11;

test.c:5:17: error: constant 0b11 is not a valid number

Kamal: add call to tolower(), since "0B11" is also a valid syntax.

Reported-by: Kamal Mostafa <kamal@canonical.com>
Signed-off-by: Dan Carpenter <error27@gmail.com>
Signed-off-by: Kamal Mostafa <kamal@canonical.com>
Signed-off-by: Christopher Li <sparse@chrisli.org>