dma_mapping_error: update to only complain about legacy kernels
The dma_mapping_error() function used to return 0 on success and
1 if there was an error.  It caused a lot of bugs, but now the
function has been modified to return -ENOMEM on failure.

I thought about removing this check completely but I decided to
modify it to only complain on stable kernels with the old
dma_mapping_error() function.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>